---
abstract: 'construct an object without type-checks'
author:
  - 'Aaron Cohen <aarondcohen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.06'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Role-UnsafeConstructable
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: '0'
  ExtUtils::MakeMaker::CPANfile: '0'
  Moose: '2.1206'
  Test::Most: '0'
  namespace::autoclean: '0'
resources:
  bugtracker: http://github.com/aarondcohen/perl-moosex-role-unsafeconstructable/issues
  homepage: http://github.com/aarondcohen/perl-moosex-role-unsafeconstructable
  repository: git://github.com/aarondcohen/perl-moosex-role-unsafeconstructable.git
version: '0.03'
